use std::fs;

use assert_cmd::Command;
use tempfile::tempdir;

#[test]
fn codebase_golden_tree_honors_gitignore() {
    let dir = tempdir().expect("create tempdir");

    fs::create_dir_all(dir.path().join("src")).expect("create src dir");
    fs::write(dir.path().join("src/main.rs"), b"fn main() {}\n").expect("write src/main.rs");

    fs::create_dir_all(dir.path().join("docs")).expect("create docs dir");
    fs::write(dir.path().join("docs/notes.md"), b"notes\n").expect("write docs/notes.md");

    fs::create_dir_all(dir.path().join("target")).expect("create target dir");
    fs::write(dir.path().join("target/junk.o"), b"junk").expect("write target/junk.o");

    fs::write(dir.path().join(".hidden"), b"secret").expect("write .hidden");
    fs::write(dir.path().join(".gitignore"), b"/target\n").expect("write .gitignore");

    Command::cargo_bin("rex")
        .expect("find rex binary")
        .args(["codebase", "--for-human"])
        .current_dir(dir.path())
        .assert()
        .success();

    let written = fs::read_to_string(dir.path().join("CODEBASE.md")).expect("read CODEBASE.md");

    let expected = "# Codebase\n\n\
        ```text\n\
        docs/\n\
        \x20\x20notes.md\n\
        src/\n\
        \x20\x20main.rs\n\
        ```\n\n\
        Generated by `rex codebase --for-human`.\n";

    assert_eq!(written, expected);
}

#[test]
fn codebase_excludes_its_own_output() {
    let dir = tempdir().expect("create tempdir");
    fs::write(dir.path().join("readme.txt"), b"hello\n").expect("write readme.txt");

    Command::cargo_bin("rex")
        .expect("find rex binary")
        .args(["codebase", "--for-human"])
        .current_dir(dir.path())
        .assert()
        .success();

    let first = fs::read_to_string(dir.path().join("CODEBASE.md")).expect("read CODEBASE.md");

    Command::cargo_bin("rex")
        .expect("find rex binary")
        .args(["codebase", "--for-human"])
        .current_dir(dir.path())
        .assert()
        .success();

    let second = fs::read_to_string(dir.path().join("CODEBASE.md")).expect("read CODEBASE.md");

    assert_eq!(
        first, second,
        "rex codebase must not include its own output in the tree"
    );
}

#[test]
fn codebase_prints_tree_to_stdout_and_writes_no_file() {
    let dir = tempdir().expect("create tempdir");
    fs::create_dir_all(dir.path().join("src")).expect("create src dir");
    fs::write(dir.path().join("src/main.rs"), b"fn main() {}\n").expect("write src/main.rs");
    fs::write(dir.path().join("readme.txt"), b"hello\n").expect("write readme.txt");

    let assert = Command::cargo_bin("rex")
        .expect("find rex binary")
        .arg("codebase")
        .current_dir(dir.path())
        .assert()
        .success();

    let stdout = String::from_utf8(assert.get_output().stdout.clone()).expect("utf8 stdout");
    assert_eq!(stdout, "readme.txt\nsrc/\n  main.rs\n");
    assert!(!dir.path().join("CODEBASE.md").exists());
}

#[test]
fn codebase_with_context_appends_first_doc_sentence() {
    let dir = tempdir().expect("create tempdir");
    let fixtures: [(&str, &str); 7] = [
        (
            "a_sentence_over_three_lines.rs",
            "//! Reads `a.md` and\n//! writes it back\n//! to disk. Then it stops.\nfn main() {}\n",
        ),
        (
            "b_full_stop_ends_first_line.rs",
            "//! First line ends here.\n//! Second line is dropped.\n",
        ),
        (
            "c_empty_doc_lines.rs",
            "//!\n//! Text with no full stop\n//!\n//! More text after a break.\n",
        ),
        (
            "d_no_full_stop.rs",
            "//! Runs until\n//! the doc lines end\nfn main() {}\n",
        ),
        ("e_no_doc.rs", "fn main() {}\n"),
        (
            "f_doc_starts_on_line_six.rs",
            "fn a() {}\nfn b() {}\nfn c() {}\nfn d() {}\nfn e() {}\n//! Too late.\n",
        ),
        ("g_not_rust.md", "//! Not a module.\n"),
    ];
    for (name, contents) in fixtures {
        fs::write(dir.path().join(name), contents).expect("write fixture");
    }

    let assert = Command::cargo_bin("rex")
        .expect("find rex binary")
        .args(["codebase", "--with-context"])
        .current_dir(dir.path())
        .assert()
        .success();

    let stdout = String::from_utf8(assert.get_output().stdout.clone()).expect("utf8 stdout");
    let expected = "\
        a_sentence_over_three_lines.rs - Reads `a.md` and writes it back to disk.\n\
        b_full_stop_ends_first_line.rs - First line ends here.\n\
        c_empty_doc_lines.rs - Text with no full stop\n\
        d_no_full_stop.rs - Runs until the doc lines end\n\
        e_no_doc.rs\n\
        f_doc_starts_on_line_six.rs\n\
        g_not_rust.md\n";
    assert_eq!(stdout, expected);
}

#[test]
fn codebase_rust_only_lists_rs_files_and_their_dirs() {
    let dir = tempdir().expect("create tempdir");
    for (path, contents) in [
        ("a/b/x.txt", "text\n"),
        ("a/c/y.rs", "fn y() {}\n"),
        ("a/z.rs", "fn z() {}\n"),
        ("docs/n.md", "notes\n"),
        ("m.rs", "fn m() {}\n"),
    ] {
        let file = dir.path().join(path);
        fs::create_dir_all(file.parent().expect("fixture has a parent")).expect("create dirs");
        fs::write(file, contents).expect("write fixture");
    }

    let assert = Command::cargo_bin("rex")
        .expect("find rex binary")
        .args(["codebase", "--rust-only"])
        .current_dir(dir.path())
        .assert()
        .success();

    let stdout = String::from_utf8(assert.get_output().stdout.clone()).expect("utf8 stdout");
    assert_eq!(stdout, "a/\n  c/\n    y.rs\n  z.rs\nm.rs\n");
}
