use std::fs;

use assert_cmd::Command;
use tempfile::tempdir;

#[test]
fn codebase_golden_tree_honors_gitignore() {
    let dir = tempdir().expect("create tempdir");

    fs::create_dir_all(dir.path().join("src")).expect("create src dir");
    fs::write(dir.path().join("src/main.rs"), b"fn main() {}\n").expect("write src/main.rs");

    fs::create_dir_all(dir.path().join("docs")).expect("create docs dir");
    fs::write(dir.path().join("docs/notes.md"), b"notes\n").expect("write docs/notes.md");

    fs::create_dir_all(dir.path().join("target")).expect("create target dir");
    fs::write(dir.path().join("target/junk.o"), b"junk").expect("write target/junk.o");

    fs::write(dir.path().join(".hidden"), b"secret").expect("write .hidden");
    fs::write(dir.path().join(".gitignore"), b"/target\n").expect("write .gitignore");

    Command::cargo_bin("rex")
        .expect("find rex binary")
        .arg("codebase")
        .current_dir(dir.path())
        .assert()
        .success();

    let written = fs::read_to_string(dir.path().join("CODEBASE.md")).expect("read CODEBASE.md");

    let expected = "# Codebase\n\n\
        ```text\n\
        docs/\n\
        \x20\x20notes.md\n\
        src/\n\
        \x20\x20main.rs\n\
        ```\n\n\
        Generated by `rex codebase`.\n";

    assert_eq!(written, expected);
}

#[test]
fn codebase_excludes_its_own_output() {
    let dir = tempdir().expect("create tempdir");
    fs::write(dir.path().join("readme.txt"), b"hello\n").expect("write readme.txt");

    Command::cargo_bin("rex")
        .expect("find rex binary")
        .arg("codebase")
        .current_dir(dir.path())
        .assert()
        .success();

    let first = fs::read_to_string(dir.path().join("CODEBASE.md")).expect("read CODEBASE.md");

    Command::cargo_bin("rex")
        .expect("find rex binary")
        .arg("codebase")
        .current_dir(dir.path())
        .assert()
        .success();

    let second = fs::read_to_string(dir.path().join("CODEBASE.md")).expect("read CODEBASE.md");

    assert_eq!(
        first, second,
        "rex codebase must not include its own output in the tree"
    );
}
