//! Generates `CODEBASE.md` — a deterministic tree outline an agent can paste
//! into a prompt to orient itself in an unfamiliar repo without spending tool
//! calls on directory walks.

use std::fs;
use std::path::Path;

use ignore::WalkBuilder;

use crate::error::RexError;

const OUTPUT_FILENAME: &str = "CODEBASE.md";

/// Walk `cwd`, skip dotfiles/gitignored paths, and write an indented tree to CODEBASE.md.
///
/// # Errors
/// - [`RexError::Walk`] if the directory walk fails (loop, glob, permissions).
/// - [`RexError::Io`] if the output file cannot be written.
pub fn run(cwd: &Path) -> Result<(), RexError> {
    let tree = render_tree(cwd)?;

    let body = format!("# Codebase\n\n```text\n{tree}```\n\nGenerated by `rex codebase`.\n");

    let out = cwd.join(OUTPUT_FILENAME);
    fs::write(&out, body.as_bytes()).map_err(|source| RexError::Io {
        path: out.clone(),
        source,
    })?;

    println!("rex codebase: wrote {}", out.display());
    Ok(())
}

fn render_tree(cwd: &Path) -> Result<String, RexError> {
    // require_git(false) so the command works in non-git dirs (tests, fresh
    // checkouts). Without it, `ignore` only honors .gitignore inside a git repo.
    let walker = WalkBuilder::new(cwd)
        .hidden(true)
        .git_ignore(true)
        .git_exclude(true)
        .git_global(true)
        .require_git(false)
        .sort_by_file_name(|a, b| a.cmp(b))
        .build();

    let mut out = String::new();
    for entry in walker {
        let entry = entry.map_err(|source| RexError::Walk {
            path: cwd.to_path_buf(),
            source,
        })?;

        let depth = entry.depth();
        if depth == 0 {
            continue;
        }

        let name = entry.file_name().to_string_lossy();
        let is_dir = entry.file_type().is_some_and(|ft| ft.is_dir());

        // Self-exclusion at depth 1 only — a nested CODEBASE.md elsewhere
        // is unusual but legitimate user content; don't silently drop it.
        if !is_dir && depth == 1 && name == OUTPUT_FILENAME {
            continue;
        }

        let indent = "  ".repeat(depth - 1);
        if is_dir {
            out.push_str(&format!("{indent}{name}/\n"));
        } else {
            out.push_str(&format!("{indent}{name}\n"));
        }
    }
    Ok(out)
}
