//! Prints a tree outline of the working directory. An agent runs it to find
//! its way around an unfamiliar repo without spending tool calls on directory
//! walks.

use std::fs::{self, File};
use std::io::{self, BufRead, BufReader, ErrorKind, Write};
use std::path::Path;

use ignore::WalkBuilder;

use crate::error::RexError;

const OUTPUT_FILENAME: &str = "CODEBASE.md";

const LAST_DOC_START_LINE: usize = 5;

const WITH_CONTEXT_FLAG: &str = "with-context";
const RUST_ONLY_FLAG: &str = "rust-only";
const FOR_HUMAN_FLAG: &str = "for-human";

/// What `rex codebase` prints and where it goes.
#[derive(clap::Args, Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct CodebaseOptions {
    /// Add the first sentence of each Rust file's `//!` doc comment to its line.
    #[arg(long = WITH_CONTEXT_FLAG)]
    pub has_context: bool,

    /// List only `.rs` files and the directories that hold at least one.
    #[arg(long = RUST_ONLY_FLAG)]
    pub is_rust_only: bool,

    /// Write the tree to CODEBASE.md instead of printing it.
    #[arg(long = FOR_HUMAN_FLAG)]
    pub is_for_human: bool,
}

impl CodebaseOptions {
    /// Builds the command line for these options. The flags always come in
    /// the same order, whatever order the user typed them in.
    fn invocation(self) -> String {
        let mut invocation = String::from("rex codebase");
        if self.is_for_human {
            invocation.push_str(&format!(" --{FOR_HUMAN_FLAG}"));
        }
        if self.is_rust_only {
            invocation.push_str(&format!(" --{RUST_ONLY_FLAG}"));
        }
        if self.has_context {
            invocation.push_str(&format!(" --{WITH_CONTEXT_FLAG}"));
        }
        invocation
    }
}

/// Walk `cwd`, skip dotfiles and gitignored paths, and print an indented tree
/// to stdout. With `is_for_human`, write the tree to CODEBASE.md instead.
///
/// # Errors
/// - [`RexError::Walk`] if the directory walk fails (loop, glob, permissions).
/// - [`RexError::Io`] if a Rust file cannot be read for its doc comment, or the
///   output file cannot be written.
/// - [`RexError::Stdout`] if the tree cannot be written to stdout.
pub fn run(cwd: &Path, options: CodebaseOptions) -> Result<(), RexError> {
    let tree = render_tree(cwd, options)?;

    if options.is_for_human {
        write_markdown_file(cwd, &tree, options)
    } else {
        print_tree(&tree)
    }
}

fn write_markdown_file(cwd: &Path, tree: &str, options: CodebaseOptions) -> Result<(), RexError> {
    let invocation = options.invocation();
    let body = format!("# Codebase\n\n```text\n{tree}```\n\nGenerated by `{invocation}`.\n");

    let out = cwd.join(OUTPUT_FILENAME);
    fs::write(&out, body.as_bytes()).map_err(|source| RexError::Io {
        path: out.clone(),
        source,
    })?;

    println!("rex codebase: wrote {}", out.display());
    Ok(())
}

fn print_tree(tree: &str) -> Result<(), RexError> {
    let mut stdout = io::stdout().lock();
    let written = stdout
        .write_all(tree.as_bytes())
        .and_then(|()| stdout.flush());

    // A reader such as `head` closing the pipe early is a normal way to use
    // this command, not a failure.
    match written {
        Err(source) if source.kind() == ErrorKind::BrokenPipe => Ok(()),
        other => other.map_err(|source| RexError::Stdout { source }),
    }
}

fn render_tree(cwd: &Path, options: CodebaseOptions) -> Result<String, RexError> {
    // require_git(false) so the command works in non-git dirs (tests, fresh
    // checkouts). Without it, `ignore` only honors .gitignore inside a git repo.
    let walker = WalkBuilder::new(cwd)
        .hidden(true)
        .git_ignore(true)
        .git_exclude(true)
        .git_global(true)
        .require_git(false)
        .sort_by_file_name(|a, b| a.cmp(b))
        .build();

    let mut out = String::new();
    // With --rust-only a directory line waits here until a Rust file shows
    // up below it, so directories with no Rust files never print.
    let mut pending_dirs: Vec<(usize, String)> = Vec::new();

    for entry in walker {
        let entry = entry.map_err(|source| RexError::Walk {
            path: cwd.to_path_buf(),
            source,
        })?;

        let depth = entry.depth();
        if depth == 0 {
            continue;
        }

        let name = entry.file_name().to_string_lossy();
        let file_type = entry.file_type();
        let is_dir = file_type.is_some_and(|ft| ft.is_dir());

        // Self-exclusion at depth 1 only — a nested CODEBASE.md elsewhere
        // is unusual but legitimate user content; don't silently drop it.
        if !is_dir && depth == 1 && name == OUTPUT_FILENAME {
            continue;
        }

        // The walk is depth-first, so a pending directory at this depth or
        // deeper has been left without a Rust file in it.
        pending_dirs.retain(|(pending_depth, _)| *pending_depth < depth);

        let indent = "  ".repeat(depth - 1);
        if is_dir {
            let line = format!("{indent}{name}/\n");
            if options.is_rust_only {
                pending_dirs.push((depth, line));
            } else {
                out.push_str(&line);
            }
            continue;
        }

        let is_rust_file = entry.path().extension().is_some_and(|ext| ext == "rs");
        if options.is_rust_only && !is_rust_file {
            continue;
        }

        for (_, line) in pending_dirs.drain(..) {
            out.push_str(&line);
        }

        out.push_str(&format!("{indent}{name}"));
        let is_regular_file = file_type.is_some_and(|ft| ft.is_file());
        if options.has_context
            && is_rust_file
            && is_regular_file
            && let Some(sentence) = first_doc_sentence(entry.path())?
        {
            out.push_str(&format!(" - {sentence}"));
        }
        out.push('\n');
    }
    Ok(out)
}

/// Reads the first sentence of the `//!` block that opens a Rust file, if it
/// has one.
///
/// The block must start within the first few lines. The sentence ends at the
/// first full stop that is followed by whitespace or the end of a line, or at
/// an empty `//!` line once text has started.
fn first_doc_sentence(path: &Path) -> Result<Option<String>, RexError> {
    let io_error = |source| RexError::Io {
        path: path.to_path_buf(),
        source,
    };

    let mut reader = BufReader::new(File::open(path).map_err(io_error)?);
    let mut raw_line = Vec::new();
    let mut text = String::new();
    let mut line_number = 0;
    let mut is_in_block = false;

    // Lines are read as bytes because `lines()` returns an error on text that
    // is not valid UTF-8, and one such file must not fail the whole command.
    while reader.read_until(b'\n', &mut raw_line).map_err(io_error)? > 0 {
        line_number += 1;
        let line = String::from_utf8_lossy(&raw_line).into_owned();
        raw_line.clear();

        let Some(doc) = line.strip_prefix("//!") else {
            if is_in_block || line_number >= LAST_DOC_START_LINE {
                break;
            }
            continue;
        };
        is_in_block = true;

        let doc = doc.trim();
        if doc.is_empty() {
            if text.is_empty() {
                continue;
            }
            break;
        }

        if !text.is_empty() {
            text.push(' ');
        }
        text.push_str(doc);

        if let Some(end) = sentence_end(&text) {
            text.truncate(end);
            break;
        }
    }

    Ok(Some(text).filter(|sentence| !sentence.is_empty()))
}

/// Finds the byte offset just past the first full stop that is followed by
/// whitespace or the end of the text. A full stop inside a word, such as
/// `CODEBASE.md`, does not count.
fn sentence_end(text: &str) -> Option<usize> {
    text.char_indices()
        .filter(|&(_, c)| c == '.')
        .map(|(index, _)| index + 1)
        .find(|&end| text[end..].chars().next().is_none_or(char::is_whitespace))
}
